language: ruby
rvm:
  - 1.8.7-head
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1.10
  - 2.3.4
  - 2.4.1
  - ruby-head

before_install:
  - gem update --system
  - gem update bundler

matrix:
  allow_failures:
  - rvm: 1.8.7-head